[WIP] Add profile page
lfglabs-dev/starknet.id pull request #3
Opened 2023-01-04 17:02 UTC by irisdv

2023-01-09 13:04 UTC, 0xBenaparte commented on components/activity.tsx
> +  const { type, description, timestamp } = props;
Tu peux directement mettre ça comme ça : 

`const Activity: FunctionComponent<ActivityData> = ({ type, description, timestamp }) => {`

2023-01-09 13:08 UTC, fricoben commented on components/clickable/clickableDiscordIcon.tsx
> +type ClickableDiscordIconProps = {
Tu répètes ce type dans plusieurs fichiers. Il a y plusieurs solutions pour éviter la répétition ici mais nous ce qu'on fait (c'est le plus simple meme si c'est pas le plus organisé) c'est de créer un `fichier type.d.ts` ou tu met les types que tu vas réutiliser plusieurs fois. 

Après en l'occurence je trouve que ça fait plus propre d'avoir le type dans le fichier ici qu'en penses tu ?

2023-01-09 13:09 UTC, 0xBenaparte commented on components/icons/discordIcon.tsx
> +export type IconProps = {
Pareil pour le type ;)

2023-01-09 13:10 UTC, 0xBenaparte commented on components/soulbound.tsx
> +export type SoulBoundData = {
`SoulBound` ==> `Soulbound` (ce n'est que 1 seul mot donc le camel case se fait comme ça je pense)

2023-01-09 13:12 UTC, 0xBenaparte commented on hooks/contracts.ts
> +        network: "goerli-alpha", // "mainnet-alpha"
On changera dans le futur ça c'est que pour tes tests c'est bien ça ? Parce que le profil sera uniquement dispo en mainnet je pense ;-)

2023-01-09 13:14 UTC, fricoben commented on pages/[id].tsx
> +              console.log("data fetched", data);
un log a enlevé 👍

2023-01-09 13:14 UTC, 0xBenaparte commented on pages/[id].tsx
> +const activityTest = [
A enlevé dans la PR final aussi

2023-01-09 13:18 UTC, 0xBenaparte commented on pages/[id].tsx
> +            NFTs & Soulbound tokens
Pour l'instant juste `Souldbounds tokens` finalement 👍

2023-01-09 13:20 UTC, 0xBenaparte commented on components/soulbound.tsx
> +      onClick={() => console.log("open")}
Rien onClick pour le moment je pense, ce log est donc à delete 👍

2023-01-09 13:24 UTC, 0xBenaparte commented on pages/[id].tsx
> +import { NextPage } from "next";
Le naming du fichier pourrait etre plus expressif pour exprimer la possibilité de mettre le .stark (ce qui est pas le cas dans notre /identities sur app.starknet.id pour le moment).

`idOrUsername` un truc du genre. Tu en penses quoi ?

2023-01-09 13:25 UTC, 0xBenaparte requested changes
Très clean ! Quelques petits changements et on fait l'api aspect puis c'est good !

2023-01-09 14:13 UTC, irisdv commented on components/clickable/clickableDiscordIcon.tsx
> +type ClickableDiscordIconProps = {
Je pense que ce serait mieux d'avoir les types dans un fichier séparé mais comme dans app.starknet.id vous les avez répété dans chaque fichier j'ai suivi la même convention :)

2023-01-09 14:15 UTC, irisdv commented on hooks/contracts.ts
> +        network: "goerli-alpha", // "mainnet-alpha"
Oui c'est pour pouvoir tester de récupérer les données du verifier. Je peux ajouter une variable d'environnement  sinon

2023-01-09 14:15 UTC, irisdv commented on pages/[id].tsx
> +import { NextPage } from "next";
Oui c'est mieux, je change!

2023-01-09 15:31 UTC, fricoben commented on components/clickable/clickableDiscordIcon.tsx
> +type ClickableDiscordIconProps = {
Ok ne répétons pas mes erreurs alors go dans un fichier séparés. Je vais le changer dans app aussi.

2023-01-09 15:31 UTC, 0xBenaparte commented on hooks/contracts.ts
> +        network: "goerli-alpha", // "mainnet-alpha"
Ok génial

2023-01-11 08:38 UTC, 0xBenaparte requested changes
Quelques petits détails mais on avance bien c'est cool.

2023-01-11 08:38 UTC, fricoben commented on components/clickable/clickableDiscordIcon.tsx
> +  // useEffect(() => {
Pq c'est commenté ? Il y avait un pb ?

2023-01-11 08:38 UTC, fricoben commented on components/clickable/clickableStarknetIcon.tsx
> +    navigator.clipboard.writeText(addr as string);
Pas besoin du `as string` ici non ? Vu que tu as typé `ClickableChainIconProps`

2023-01-11 08:38 UTC, 0xBenaparte commented on components/clickable/clickableStarknetIcon.tsx
> +          addr.substring(addr.length - 4, addr.length)}
On a une fonction testée sur l'app (pas besoin de la tester ici) pour ça ici que tu peux réutiliser. 

```
export function minifyAddress(address: string): string {
  const firstPart = address.substring(0, 4);
  const secondPart = address.substring(address.length - 3, address.length);

  return (firstPart + "..." + secondPart).toLowerCase();
}
```

2023-01-11 08:38 UTC, 0xBenaparte commented on components/soulbound.tsx
> +      setUrl(imageUri.replace("ipfs://", "https://ipfs.io/ipfs/"));
Bien vu ça 👍

2023-01-11 08:38 UTC, 0xBenaparte commented on constants.ts
> +  JediSwap: "0x2bcc885342ebbcbcd170ae6cafa8a4bed22bb993479f49806e72d96af94c965",
a placer dans utils je pense ou autre part que dans la racine du dossier non ?

2023-01-11 08:38 UTC, 0xBenaparte commented on utils/stringService.ts
> +export function minifyAddressOrDomain(
je viens de faire une PR pour changer cette fonction ``minifyAddressOrDomain`` utils qui est nul et faire des trucs plus clean.

https://github.com/starknet-id/app.starknet.id/pull/87/files

2023-01-13 12:25 UTC, Th0rgal commented
![image](https://user-images.githubusercontent.com/41830259/212319913-9a52df0f-d03d-4d4b-991d-a72115e7dcac.png)
erreur de build apparemment

2023-01-23 15:25 UTC, 0xBenaparte approved these changes

2023-01-23 18:43 UTC, merged